name: lint

env:
  GOPATH: /home/runner/work/christwosix/go

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.23.0']
    steps:
      - name: Configure Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Lint source
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60.3
